### ISSUE TITLE
Can't package chart with dependency in chartcenter

### ISSUE THREAD

**Issue by d-m** [jfrog/chartcenter-plugin#3]
When trying to use this plugin to package a chart with a dependency from chartcenter.io, it fails with the following error:

```
Packaging my-chart-1.0.0
9.4.4.tgz
tar: 9.4.4.tgz: Cannot stat: No such file or directory
tar: Error exit delayed from previous errors.
Error: plugin "center" exited with error
```

It looks like this line grabs all the `version:` lines, including those in the dependencies, causing it to fail:

https://github.com/jfrog/chartcenter-plugin/blob/dcc58a18fea19a7c5d5822200ee9d9b1eefa5fc5/scripts/center.sh#L18

Example Chart.yaml:

```yaml
version: 1.0.0

dependencies:
- name: prometheus-community/kube-prometheus-stack
  version: 9.4.4
  repository: "https://repo.chartcenter.io"
```
